# REACHER
GAMMA = 0.99
GRADIENT_CLIP = 0.01
ENTROPY_WEIGHT = 0.001
VALUE_LOS_WEIGHT = 1.0
ACTIONS_BETWEEN_LEARNING = 5
ROLLOUT_LENGTH = 5
NOISE_ON_THE_ACTIONS = 1e-3
NOISE_REDUCTION_FACTOR = 0.99


# Crawler
GAMMA = 0.99
GRADIENT_CLIP = 0.01
ENTROPY_WEIGHT = 0.001
VALUE_LOS_WEIGHT = 1.0
ACTIONS_BETWEEN_LEARNING = 5
ROLLOUT_LENGTH = 5
NOISE_ON_THE_ACTIONS = 1e-3
NOISE_REDUCTION_FACTOR = 0.99
